---
resources:
  - name: docker-images
    type: git
    source:
      uri: https://github.com/caraka/docker-images.git
      branch: master

  - name: httpd-py-cgi
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: ((docker-hub-username))/httpd-py-cgi
      tag: 2.4

jobs:
  - name: build-httpd-py-cgi
    public: true
    plan:
      - get: git-repo
      - put: httpd-py-cgi
        params:
          build: docker-images/httpd-py-cgi/docker

